### ISSUE TITLE
How do I do ?

### ISSUE THREAD

**Issue by Gluups** [atomsk-0/NativeFiledialogNET#1]
Hello,
The NativeFileDialogNET solution compiles, that is nice to begin with.
Unfortunately I have to confess shortcomings about how to execute the test.
I guess the code that is provided is in C#, I created a console program with the code in the Program.cs file, included in the same solution as NativeFileDialogNET.
I get 11 compilation errors, including that collections expressions are not available in C# 9.
Once I modify the project file to use version 12 of C#, I presume I have to put nfd.dll in the execution directory of the test program?
Any other directive to provide?
By the way, the first use I intend to do is select a directory with OpenFileDialog.

**Comment by atomsk-0** [comment]
which .NET version your console project is? If you add NativeFileDialogNET to the project as nuget package the dll should be automatically copied to the build directory in runtimes folder

**Comment by atomsk-0** [comment]
>  By the way, the first use I intend to do is select a directory with OpenFileDialog.

Currently there's only file select modes added i plan to add rest stuff to this repo really soon.

**Comment by Gluups** [comment]
Very good question, thank you for its quickness.
The test program was in .Net 6, the errors number decreased to 9 after I upgraded to .Net 8.
It seems I have to reference the DLL, as I have an error on the using line. This can be coherent with dialogResult not recognised.

**Comment by Gluups** [comment]
As NuGet Package ? OK, I should have tried to add the DLL in the references.
Oh, only file select for the moment being?
I shall try when you complete: having a solution that compiles directly after downloading is an interesting point :)

**Comment by Gluups** [comment]
To insert the NuGet package I had to give its name without its path.
Then I get an openfiledialog, followed by a savefiledialog.
It seems this is what you planed.

**Comment by Gluups** [comment]
I understood much better what happened after adding `Console.ReadKey()` at the end.
So, you took care of testing the dialogResult.
I presume the difference is about the default value.
With common dialog it is the first button, whereas your dialog box is not closed until the user chooses a button.
