### ISSUE TITLE
Add Support for Multi-Select

### ISSUE THREAD

**Issue by AeonSake** [atomsk-0/NativeFiledialogNET#4]
The `nativefiledialog-extended` library seems to have support for opening multiple files or folders (via `OpenDialogMultiple` and `PickFolderMultiple`). It would be great to have support for that in this library as well.

**Comment by atomsk-0** [comment]
Support for allowing user to select multiple files or folders is now added in 2.0.2 nuget. You can allow it by adding .AllowMultiple() after u have called SelectFolder or SelectFile and change output from string? to string[]?
