### ISSUE TITLE
Native Runtimes for Linux

### ISSUE THREAD

**Issue by MiniMe453** [atomsk-0/NativeFiledialogNET#5]
I was testing this with Windows and it works great, however when I moved to Linux to test, the nfd.dll file is not found. I looked into the NuGet package and couldn't see any build binaries for anything other than Windows-x64. 

I wanted to ask if I am missing something here or if I need to build the linux binaries from source. It would be great if they were included as part of the NuGet package.

Thanks!

**Comment by atomsk-0** [comment]
I only have provided currently ready compiled shared library for windows, but ill look into adding github workflow to compile them automatically for linux and macos too

**Comment by MiniMe453** [comment]
That would be amazing! Thanks :)

**Comment by atomsk-0** [comment]
Linux and macos runtimes should now be included in 2.0.2 nuget version once it gets validated and indexed

**Comment by MiniMe453** [comment]
Awesome <3 I will check it out when I am off work and have some time. thank you!!
